# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dien Bui's blog
email: dienbuijoe@outlook.com
url: "https://joebui.github.io" # the base hostname & protocol for your site
github_username:  joebui

# Build settings
markdown: kramdown
# Plugins
gems:
    - jekyll-paginate
    - jekyll-coffeescript
    - jekyll-seo-tag

paginate: 10
